name: ci-test

on:
  push:
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != '{{INIT_COMMIT_MESSAGE}}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Cache helm-unittest
        uses: actions/cache@v4
        with:
          path: ~/.local/share/helm/plugins/helm-unittest
          key: unittest-${{ runner.os }}-${{ hashFiles('**/Chart.yaml') }}

      - name: helm lint
        run: helm lint .

      - name: helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false || true
          helm unittest .

      - name: kind create cluster
        uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:v1.30.0
          cluster_name: ci

      - name: helm install & test
        run: |
          RELEASE="ci-${{ github.run_id }}"
          helm install "$RELEASE" . --wait --timeout 120s
          helm test "$RELEASE" --timeout 120s || {
            kubectl logs -l app.kubernetes.io/instance="$RELEASE" --all-containers=true
            exit 1
          }
          helm delete "$RELEASE"

  create-pr:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      !contains(github.ref, 'main') &&
      !contains(github.ref, 'master') &&
      contains(github.event.head_commit.message, '{{PR_MARK_TEXT}}')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch default branch
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}:${{ github.event.repository.default_branch }}

      - name: Detect base branch
        id: main
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/main; then
            echo "name=main" >> $GITHUB_OUTPUT
          else
            echo "name=master" >> $GITHUB_OUTPUT
          fi

      - name: Ensure label exists
        run: |
          gh api repos/${{ github.repository }}/labels \
            --field name='automated' \
            --field color='EDEDED' \
            --field description='Created by CI' \
            || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list --head "${{ github.ref_name }}" --json number --jq '.[0].number' | grep -q .; then
            echo "PR already exists, skip."
            exit 0
          fi

          gh pr create \
            --base  ${{ steps.main.outputs.name }} \
            --head  "${{ github.ref_name }}" \
            --title "Auto PR: ${{ github.ref_name }}" \
            --body  "Generated by workflow \`ci-test\`  \
                     Commit: ${{ github.sha }}  \
                     Author: ${{ github.actor }}" \
            --label automated

          # gh pr merge --squash --auto "${{ github.ref_name }}"