name: Auto Tag

on:
  pull_request:
    types: [closed]
    branches: [main, master]
    paths:
      - 'Chart.yaml'

permissions:
  contents: write

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect version change
        id: detect
        run: |
          # 获取合并前的版本号
          OLD_VERSION=$(git show HEAD~1:Chart.yaml | grep '^version:' | awk '{print $2}')
          # 获取合并后的版本号
          NEW_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          
          echo "old_version=${OLD_VERSION}" >> $GITHUB_OUTPUT
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          
          # 比较版本号是否变化
          if [ "${OLD_VERSION}" != "${NEW_VERSION}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from ${OLD_VERSION} to ${NEW_VERSION}"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Version unchanged: ${NEW_VERSION}"
          fi

      - name: Create and push tag
        if: steps.detect.outputs.changed == 'true'
        run: |
          # 配置 git 用户信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 创建并推送 tag
          VERSION="${{ steps.detect.outputs.new_version }}"
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
          
          echo "Created and pushed tag: v${VERSION}"
