name: ci-test

on:
  push:
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Cache helm-unittest
        uses: actions/cache@v4
        with:
          path: ~/.local/share/helm/plugins/helm-unittest
          key: unittest-${{ runner.os }}-${{ hashFiles('**/Chart.yaml') }}

      - name: helm lint
        run: helm lint .

      - name: helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false || true
          helm unittest .

      - name: kind create cluster
        uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:v1.30.0
          cluster_name: ci

      - name: helm install & test
        run: |
          RELEASE="ci-${{ github.run_id }}"
          helm install "$RELEASE" . --wait --timeout 120s
          helm test "$RELEASE" --timeout 120s || {
            kubectl logs -l app.kubernetes.io/instance="$RELEASE" --all-containers=true
            exit 1
          }
          helm delete "$RELEASE"