{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "{{CHART_NAME}}.fullname" . }}
  labels:
    release: {{ .Values.serviceMonitor.release }}
spec:
  selector:
    matchLabels:
      {{- include "{{CHART_NAME}}.labels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval | default "15s" }}
    path: {{ .Values.serviceMonitor.path | default "/metrics" }}
{{- end }}